accounts/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts.views import AccountRegisterView, AccountProfileView, RecommendationDetail, AccountLogoutView

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', AccountProfileView.as_view(), name='profile') ,
    path('recommendation/<int:pk>', RecommendationDetail.as_view(), name='recommendation'),
]

litmatch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('predictions/', include('predictions.urls', namespace='predictions')),
    path('', TemplateView.as_view(template_name='layout.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

predictions/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import GetPrediction, GetLitMatch

app_name = 'predictions'

urlpatterns = [
    path('', GetPrediction.as_view(), name='index'),
    path('match', GetLitMatch.as_view(), name='match'),
]

templates/layout.html
{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}LitMatch{% endblock %}</title>
    {% block stylesheets %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">LitMatch</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'predictions:index' %}">Get Your LitMatch</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div>
      {% block content %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
  </body>
</html>